### ISSUE TITLE
It keeps checking my local database

### ISSUE THREAD

**Issue by elmirb123** [pmill/laravel-aws-cognito#1]
Hello,

To be able to log in, the package requires me to have the user both in my local database and in Cognito pool. Is this expected behavior or am I doing something wrong?

**Comment by pmill** [comment]
Yeah, that's how I intended this to work for my particular use case. Can you detail how you expect this to work and I'll see if I can make changes that would suit both workflows.

**Comment by elmirb123** [comment]
Well what I thought is that it would only check Cognito credentials and if they are valid, authenticate the user. 

I would be grateful if you can make the changes, or at least point me in the right direction.

Kind regards

**Comment by pmill** [comment]
Is my other aws cognito package something that would be more appropriate for you?

https://github.com/pmill/aws-cognito

If not is it literally just the username/password login to return an accessToken/refreshToken or error if invalid the functionality that you need?

**Comment by elmirb123** [comment]
Yes, I managed to get it to work like I want it to.

Thanks a lot!
